### PR TITLE
Bug/#4 - Mask indexing issues and small fixes

### LINKED ISSUE #4: Fix mask indexing bug.
See discussion at https://github.com/InsightSoftwareConsortium/ITKBoneMorphometry/pull/13

### PR DESCRIPTION
**Pull request by Besler**
This resolves #4. I do not explicitly handle the case of the mask being larger than the input image. Instead, if the mask is bigger there will be an error on `Update()`. In the `ThreadedGenerateDataMethod`, a image region crop is performed to compute the intersection of this threads region and the mask region. This should speed up computation.

I also corrected two other bugs. First, I removed inappropriate `const_cast`.  Next, I added `Modified()` to the setters of `KrcahEigenToScalarImageFilter`.

### CODE REVIEW

File: include/itkKrcahEigenToScalarImageFilter.hxx [hunk 1]
```diff
@@ -41,11 +41,16 @@ KrcahEigenToScalarImageFilter< TInputImage, TOutputImage, TMaskImage >
...
 {
   Superclass::GenerateInputRequestedRegion();
+
   if ( this->GetInput() )
   {
-  typename TInputImage::Pointer image =
-    const_cast< TInputImage * >( this->GetInput() );
-  image->SetRequestedRegionToLargestPossibleRegion();
+    InputImagePointer image = const_cast< typename Superclass::InputImageType * >( this->GetInput() );
+    image->SetRequestedRegionToLargestPossibleRegion();
```
Comment (thewtex) [inline include/itkKrcahEigenToScalarImageFilter.hxx]: This will limit streaming of the input image and mask, which is fine for now. In the future, if we need to process very large images on systems with limited memory, we can work to set the `RequestedRegion`'s to only the regions required.

**Comment by Besler** [comment]
Sorry, fell behind merging this earlier. Thanks!

File: include/itkKrcahEigenToScalarImageFilter.hxx (hunk 1 above)
Comment (Besler) [reply include/itkKrcahEigenToScalarImageFilter.hxx]: Yes, good point. Here, parameter estimation takes the 'maximum over all voxels'. Is there a good way to do such an operation with streaming in itk?

Comment (thewtex) [reply include/itkKrcahEigenToScalarImageFilter.hxx]: In practice, we may need to make the maximum a separate input so it can be computed in a streamed way outside of the filter.
